- .prettierrc
- components/SignUp.js
- lib/api.js
- package.json
This PR updates `from` number to use verified number in twilio. It also uses the `to` number from request the body. An additional form field for phone number is also added.
> CLT-1 | update form and backend numbers phone numbers

- package.json
> CLT-2 | add husky and eslint

- package.json
- tslint.json
This PR update prettier lint-stage settings and rules for the pre-commit hook.
> CLT-4 | update prettier lint-stage settings

- lib/games.ts
- package.json
- pages/games/index.js
Games that have ended should say `Game Over`.
> CLT-5 | disable ended games

- components/CreateGameForm.tsx
- pages/_error.js
- pages/dashboard/create.js
- pages/dashboard/index.js
Can now change color
Cleaner UX for setting emoji and options
Bad urls go str8 to home page
> improving the create game card + handling 404s

- components/CreateGameForm.tsx
- now.json
- pages/games/create.js
- pages/games/index.js
- server/handlers/post.js
- server/helpers/game.js
This PR updates existing logic to support user-submitted games.
Up Next:
- confirmation messages after questions are submitted
- admin dashboard for approving the user-submitted question
> CLT | create user submitted games

- pages/games/create.js
- pages/games/index.js
This PR updates card to have a unique key.
> CLT | fix bug with card opening

- pages/games/create.js
- pages/games/index.js
For some reason the [<Link>](https://nextjs.org/docs/api-reference/next/link) tag outside of that specific <div> was not working so I removed the Link tag
> Fixed create game bug

- components/GameTable.tsx
- components/Modal.tsx
- pages/confirmation/[wager].js
- pages/dashboard/users/games.js
- pages/games/create/confirmation.js
- pages/payouts/confirm.js
current: `Your Submission been received!`
updated: `Your Submission has been received!`
> CLT | fix grammar in header

- pages/confirmation/[wager].js
- pages/games/create/confirmation.js
- pages/payouts/confirm.js
current: `Your Submission has been received!`
updated: `Your submission has been received!`
> CLT | fix grammar in header to capitalize

- components/DisclaimerModal.tsx
- package.json
- pages/index.js
- pages/signup.js
This PR adds a disclaimer modal to index and signup.
> CLT | update credit disclaimers

- pages/index.js
- pages/signup.js
previous: `Sign up today to receive a free $5 towards your bets.`
updated:  `Sign up today to receive a free $5 credit towards your bets.`
> CLT | add credit

- components/DisclaimerModal.tsx
- pages/index.js
- pages/signup.js
- server/helpers/user.js
Change new user credit to $2 from $5.
> CLT | update credit to 2

- components/DisclaimerModal.tsx
> CLT | update disclaimer text

- pages/index.js
- pages/signup.js
This PR adds `Also, for a limited time enjoy feeless bets!`.
> CLT | add fee note

- components/forms/CreateGameForm.tsx
- pages/dashboard/create.js
- pages/dashboard/edit/[game].js
- pages/games/create/index.js
> CLT | add user id to game

- server/helpers/game.js
This PR fixes a DB bug where user create game record was being updated and not inserting a new one
> CLT | update to insert one

- pages/games/create/confirmation.js
change from `julius` to `info`
> CLT | update confirmation email to info

- pages/games/[game].js
- pages/games/xxl.js
- server/helpers/stripe.js
- server/helpers/user.js
> CLT | destructure optimizations

- components/forms/LoginForm.tsx
- components/forms/PasswordResetForm.tsx
- lib/firebase/index.js
- pages/user/pw-forget.js
This PR creates a password reset page and component. Users are prompted to reset their password followed by receiving a reset link to their email.
https://www.loom.com/share/41f2764e88d944c0bb8e3792f114cd1a
> CLT | create forgot password integration

- components/admin/GameTable.tsx
- components/forms/CreateGameForm.tsx
- now.json
- now.staging.json
- pages/dashboard/index.js
- pages/dashboard/users/games.js
- server/handlers/get.js
- server/handlers/post.js
- server/helpers.js
- server/helpers/game.js
Add user-submitted questions to the dashboard. This update is read-only
TODO: allow admin to add/delete questions from the dashboard.
> CLT | create user submitted question dashboard

- components/forms/PasswordChangeForm.tsx
- components/forms/PasswordResetForm.tsx
- components/layout/UserDashNavigation.tsx
- lib/firebase/index.js
- pages/user/change-password.js
This PR adds change password logic to the user dashboard. After a user resets the dashboard they're redirected back to the page they were on.
https://www.loom.com/share/fd7c74ed75b341b9aa5452f2188c0c96
> CLT | change password integration

- components/forms/PasswordChangeForm.tsx
Increase timeout to 3 milliseconds.
> CLT | increase time to 3 milliseconds

- components/admin/GameTable.tsx
This PR links user ID to their account management page.
> CLT | add link to manage user

- pages/index.js
- pages/learnmore.js
Remove text saying double your money.
> CLT | remove double from site

- components/layout/Navigation.tsx
- components/layout/Wrapper.js
- package.json
- pages/_app.js
- public/static/nprogress.css
This PR adds a progress bar while navigating the site.
> CLT | add loading progress bar

- pages/games/index.js
This PR wraps create a game in a Link component
> CLT | wrap in Link component

- components/layout/Navigation.tsx
- components/layout/Wrapper.js
This PR adds a logout link to the navigation bar.
> CLT | add logout link to navigation

- pages/dashboard/index.js
> CLT | wrap create game in Link

- server/helpers/game.js
> Revert "CLT | fix: update handle payouts to work for bets from same user"
